# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 1

before:
  hooks:
    - go mod tidy
    - weaver generate ./frame ./serviceimpl/admin/ ./serviceimpl/blog/ ./serviceimpl/customwidget/ ./serviceimpl/customwidget/service ./serviceimpl/forum/ ./serviceimpl/login/ ./serviceimpl/markdown/ ./serviceimpl/passwordstrength/ ./serviceimpl/profile/ ./serviceimpl/salt/ ./serviceimpl/session/ ./serviceimpl/settings/ ./serviceimpl/templates/ ./serviceimpl/wiki/

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
      - solaris

    goarch:
      - amd64
      - arm64

release:
  name_template: "Release {{.Tag}}"

changelog:
  use: github-native

archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{- .Os }}_{{- .Arch }}"

nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}'
    maintainer: 'https://github.com/dvaumoron'
    homepage: https://github.com/dvaumoron/puzzleweaver
    description: >-
      A ServiceWeaver (https://serviceweaver.dev) compatible modified version of PuzzleWeb (https://github.com/dvaumoron/puzzleweb), embeds all backing services.
    license: "Apache-2.0"
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    section: default
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/puzzleweaver/copyright
        file_info:
          mode: 0444
    rpm:
      signature:
        key_file: "{{ if index .Env \"GPG_KEY_FILE\"  }}{{.Env.GPG_KEY_FILE}}{{ end }}"
    deb:
      signature:
        key_file: "{{ if index .Env \"GPG_KEY_FILE\"  }}{{.Env.GPG_KEY_FILE}}{{ end }}"

brews:
  - repository:
      owner: dvaumoron
      name: homebrew-tap
    directory: Formula
    homepage: https://github.com/dvaumoron/puzzleweaver
    description: A ServiceWeaver (https://serviceweaver.dev) compatible modified version of PuzzleWeb (https://github.com/dvaumoron/puzzleweb), embeds all backing services
    license: "Apache-2.0"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
