[serviceweaver]
name   = "PuzzleWeaver"
binary = "../../../../bin/puzzleweaver"

[single]
listeners.web = { address = "localhost:8080" }

[multi]
listeners.web = { address = "localhost:8080" }

["github.com/ServiceWeaver/weaver/Main"]
domain             = "localhost"
port               = "8080"
defaultlang        = "fr-FR"
sessiontimeout     = 1200
servicetimeout     = "5s"
maxmultipartmemory = 0
dateformat         = "2/1/2006 15:04:05"
pagesize           = 3
extractsize        = 200
feedformat         = "rss"
feedsize           = 100

fsconf           = { kind = "local" }
staticpath       = "static"
faviconpath      = "favicon.ico"
page404url       = "/notFound"
langpicturepaths = { "fr-FR" = "images/Flag_of_France.webp", "en-US" = "images/Flag_of_the_United_Kingdom.png" }

profilegroupid            = 0
profiledefaultpicturepath = "static/images/unknownuser.png"

pagegroups = [{ id = 0, pages = ["about/", "about/faq"] }]
widgetpages = [
    { emplacement = "about", name = "wiki", widgetref = "wiki1" },
    { emplacement = "about/faq", name = "wiki2", widgetref = "wiki2" },
    { name = "wiki3", widgetref = "wiki3" },
    { name = "blog", widgetref = "blog" },
    { name = "forum", widgetref = "forum" },
    { name = "gallery", widgetref = "gallery" },
]

ginreleasemode = true

["github.com/ServiceWeaver/weaver/Main".widgets.wiki1]
kind     = "wiki"
objectid = 1
groupid  = 2
["github.com/ServiceWeaver/weaver/Main".widgets.wiki2]
kind      = "wiki"
objectid  = 2
groupid   = 2
templates = ["Welcome", "wiki2/view", "wiki2/edit", "wiki2/list"]
["github.com/ServiceWeaver/weaver/Main".widgets.wiki3]
kind     = "wiki"
objectid = 3
groupid  = 3
["github.com/ServiceWeaver/weaver/Main".widgets.blog]
kind     = "blog"
objectid = 4
groupid  = 4
["github.com/ServiceWeaver/weaver/Main".widgets.forum]
kind     = "forum"
objectid = 5
groupid  = 5
["github.com/ServiceWeaver/weaver/Main".widgets.gallery]
kind       = "remote"
widgetname = "gallery"
objectid   = 6
groupid    = 0

["github.com/dvaumoron/puzzleweaver/serviceimpl/session/SessionService"]
sessiontimeout = "1260s"
retrynumber    = 100
redisaddress   = "localhost:6379"
redisuser      = ""
redispassword  = ""
redisdbnum     = 0
debug          = false

["github.com/dvaumoron/puzzleweaver/serviceimpl/templates/TemplateService"]
alllang        = ["fr-FR", "en-US"]
fsconf         = { kind = "local" }
componentspath = "templatedata/templates/components"
viewspath      = "templatedata/templates/views"
localefilepath = "templatedata/locales/messages_{{lang}}.properties"
dateformat     = "2/1/2006 15:04:05"

["github.com/dvaumoron/puzzleweaver/serviceimpl/settings/SettingsService"]
mongoaddress      = "mongodb://localhost:27017"
mongodatabasename = "settingsDB"

["github.com/dvaumoron/puzzleweaver/serviceimpl/passwordstrength/PasswordStrengthService"]
defaultpassword = "Password@1234"
alllang         = ["fr-FR", "en-US"]
fsconf          = { kind = "local" }
rulefilepath    = "../puzzlepassstrengthserver/rules/rules_{{lang}}.txt"

["github.com/dvaumoron/puzzleweaver/serviceimpl/salt/SaltService"]
redisaddress  = "localhost:6379"
redisuser     = ""
redispassword = ""
redisdbnum    = 2
saltlen       = 64

["github.com/dvaumoron/puzzleweaver/serviceimpl/login/RemoteLoginService"]
databasekind    = "postgres"
databaseaddress = "host=localhost user=postgres dbname=logindb port=5432 sslmode=disable"

["github.com/dvaumoron/puzzleweaver/serviceimpl/admin/AdminService"]
databasekind    = "postgres"
databaseaddress = "host=localhost user=postgres dbname=rightdb port=5432 sslmode=disable"
fsconf          = { kind = "local" }
opamodulepath   = "../puzzlerightserver/auth_rule.rego"

permissiongroups = [
    { id = 2, name = "wikiGroup1" },
    { id = 3, name = "wikiGroup2" },
    { id = 4, name = "blogGroup" },
    { id = 5, name = "forumGroup" },
]

["github.com/dvaumoron/puzzleweaver/serviceimpl/profile/RemoteProfileService"]
mongoaddress      = "mongodb://localhost:27017"
mongodatabasename = "profilesDB"

["github.com/dvaumoron/puzzleweaver/serviceimpl/forum/RemoteForumService"]
databasekind    = "postgres"
databaseaddress = "host=localhost user=postgres dbname=forumdb port=5432 sslmode=disable"

["github.com/dvaumoron/puzzleweaver/serviceimpl/markdown/MarkdownService"]
# no configuration needed for markdown

["github.com/dvaumoron/puzzleweaver/serviceimpl/blog/RemoteBlogService"]
mongoaddress      = "mongodb://localhost:27017"
mongodatabasename = "blogsDB"

["github.com/dvaumoron/puzzleweaver/serviceimpl/wiki/RemoteWikiService"]
mongoaddress      = "mongodb://localhost:27017"
mongodatabasename = "wikisDB"

["github.com/dvaumoron/puzzleweaver/serviceimpl/remotewidget/RemoteWidgetService"]
gallerymongoaddress      = "mongodb://localhost:27017"
gallerymongodatabasename = "galleriesDB"
defaultpagesize          = 2
