// Code generated by "weaver generate". DO NOT EDIT.
//go:build !ignoreWeaverGen

package wikiimpl

import (
	"context"
	"errors"
	"fmt"
	"github.com/ServiceWeaver/weaver"
	"github.com/ServiceWeaver/weaver/runtime/codegen"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
	"reflect"
)

func init() {
	codegen.Register(codegen.Registration{
		Name:  "github.com/dvaumoron/puzzleweaver/serviceimpl/wiki/RemoteWikiService",
		Iface: reflect.TypeOf((*RemoteWikiService)(nil)).Elem(),
		Impl:  reflect.TypeOf(remoteWikiImpl{}),
		LocalStubFn: func(impl any, caller string, tracer trace.Tracer) any {
			return remoteWikiService_local_stub{impl: impl.(RemoteWikiService), tracer: tracer, deleteMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/dvaumoron/puzzleweaver/serviceimpl/wiki/RemoteWikiService", Method: "Delete", Remote: false}), getVersionsMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/dvaumoron/puzzleweaver/serviceimpl/wiki/RemoteWikiService", Method: "GetVersions", Remote: false}), loadMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/dvaumoron/puzzleweaver/serviceimpl/wiki/RemoteWikiService", Method: "Load", Remote: false}), storeMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/dvaumoron/puzzleweaver/serviceimpl/wiki/RemoteWikiService", Method: "Store", Remote: false})}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any {
			return remoteWikiService_client_stub{stub: stub, deleteMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/dvaumoron/puzzleweaver/serviceimpl/wiki/RemoteWikiService", Method: "Delete", Remote: true}), getVersionsMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/dvaumoron/puzzleweaver/serviceimpl/wiki/RemoteWikiService", Method: "GetVersions", Remote: true}), loadMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/dvaumoron/puzzleweaver/serviceimpl/wiki/RemoteWikiService", Method: "Load", Remote: true}), storeMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/dvaumoron/puzzleweaver/serviceimpl/wiki/RemoteWikiService", Method: "Store", Remote: true})}
		},
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return remoteWikiService_server_stub{impl: impl.(RemoteWikiService), addLoad: addLoad}
		},
		ReflectStubFn: func(caller func(string, context.Context, []any, []any) error) any {
			return remoteWikiService_reflect_stub{caller: caller}
		},
		RefData: "",
	})
}

// weaver.InstanceOf checks.
var _ weaver.InstanceOf[RemoteWikiService] = (*remoteWikiImpl)(nil)

// weaver.Router checks.
var _ weaver.Unrouted = (*remoteWikiImpl)(nil)

// Local stub implementations.

type remoteWikiService_local_stub struct {
	impl               RemoteWikiService
	tracer             trace.Tracer
	deleteMetrics      *codegen.MethodMetrics
	getVersionsMetrics *codegen.MethodMetrics
	loadMetrics        *codegen.MethodMetrics
	storeMetrics       *codegen.MethodMetrics
}

// Check that remoteWikiService_local_stub implements the RemoteWikiService interface.
var _ RemoteWikiService = (*remoteWikiService_local_stub)(nil)

func (s remoteWikiService_local_stub) Delete(ctx context.Context, a0 uint64, a1 string, a2 uint64) (err error) {
	// Update metrics.
	begin := s.deleteMetrics.Begin()
	defer func() { s.deleteMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "wikiimpl.RemoteWikiService.Delete", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.Delete(ctx, a0, a1, a2)
}

func (s remoteWikiService_local_stub) GetVersions(ctx context.Context, a0 uint64, a1 string) (r0 []RawWikiContent, err error) {
	// Update metrics.
	begin := s.getVersionsMetrics.Begin()
	defer func() { s.getVersionsMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "wikiimpl.RemoteWikiService.GetVersions", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.GetVersions(ctx, a0, a1)
}

func (s remoteWikiService_local_stub) Load(ctx context.Context, a0 uint64, a1 string, a2 uint64) (r0 RawWikiContent, err error) {
	// Update metrics.
	begin := s.loadMetrics.Begin()
	defer func() { s.loadMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "wikiimpl.RemoteWikiService.Load", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.Load(ctx, a0, a1, a2)
}

func (s remoteWikiService_local_stub) Store(ctx context.Context, a0 uint64, a1 uint64, a2 string, a3 uint64, a4 string) (err error) {
	// Update metrics.
	begin := s.storeMetrics.Begin()
	defer func() { s.storeMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "wikiimpl.RemoteWikiService.Store", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.Store(ctx, a0, a1, a2, a3, a4)
}

// Client stub implementations.

type remoteWikiService_client_stub struct {
	stub               codegen.Stub
	deleteMetrics      *codegen.MethodMetrics
	getVersionsMetrics *codegen.MethodMetrics
	loadMetrics        *codegen.MethodMetrics
	storeMetrics       *codegen.MethodMetrics
}

// Check that remoteWikiService_client_stub implements the RemoteWikiService interface.
var _ RemoteWikiService = (*remoteWikiService_client_stub)(nil)

func (s remoteWikiService_client_stub) Delete(ctx context.Context, a0 uint64, a1 string, a2 uint64) (err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.deleteMetrics.Begin()
	defer func() { s.deleteMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "wikiimpl.RemoteWikiService.Delete", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += 8
	size += (4 + len(a1))
	size += 8
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.Uint64(a0)
	enc.String(a1)
	enc.Uint64(a2)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 0, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	err = dec.Error()
	return
}

func (s remoteWikiService_client_stub) GetVersions(ctx context.Context, a0 uint64, a1 string) (r0 []RawWikiContent, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.getVersionsMetrics.Begin()
	defer func() { s.getVersionsMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "wikiimpl.RemoteWikiService.GetVersions", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += 8
	size += (4 + len(a1))
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.Uint64(a0)
	enc.String(a1)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 1, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = serviceweaver_dec_slice_RawWikiContent_44c17df6(dec)
	err = dec.Error()
	return
}

func (s remoteWikiService_client_stub) Load(ctx context.Context, a0 uint64, a1 string, a2 uint64) (r0 RawWikiContent, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.loadMetrics.Begin()
	defer func() { s.loadMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "wikiimpl.RemoteWikiService.Load", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += 8
	size += (4 + len(a1))
	size += 8
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.Uint64(a0)
	enc.String(a1)
	enc.Uint64(a2)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 2, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	(&r0).WeaverUnmarshal(dec)
	err = dec.Error()
	return
}

func (s remoteWikiService_client_stub) Store(ctx context.Context, a0 uint64, a1 uint64, a2 string, a3 uint64, a4 string) (err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.storeMetrics.Begin()
	defer func() { s.storeMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "wikiimpl.RemoteWikiService.Store", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += 8
	size += 8
	size += (4 + len(a2))
	size += 8
	size += (4 + len(a4))
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.Uint64(a0)
	enc.Uint64(a1)
	enc.String(a2)
	enc.Uint64(a3)
	enc.String(a4)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 3, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	err = dec.Error()
	return
}

// Note that "weaver generate" will always generate the error message below.
// Everything is okay. The error message is only relevant if you see it when
// you run "go build" or "go run".
var _ codegen.LatestVersion = codegen.Version[[0][20]struct{}](`

ERROR: You generated this file with 'weaver generate' v0.21.2 (codegen
version v0.20.0). The generated code is incompatible with the version of the
github.com/ServiceWeaver/weaver module that you're using. The weaver module
version can be found in your go.mod file or by running the following command.

    go list -m github.com/ServiceWeaver/weaver

We recommend updating the weaver module and the 'weaver generate' command by
running the following.

    go get github.com/ServiceWeaver/weaver@latest
    go install github.com/ServiceWeaver/weaver/cmd/weaver@latest

Then, re-run 'weaver generate' and re-build your code. If the problem persists,
please file an issue at https://github.com/ServiceWeaver/weaver/issues.

`)

// Server stub implementations.

type remoteWikiService_server_stub struct {
	impl    RemoteWikiService
	addLoad func(key uint64, load float64)
}

// Check that remoteWikiService_server_stub implements the codegen.Server interface.
var _ codegen.Server = (*remoteWikiService_server_stub)(nil)

// GetStubFn implements the codegen.Server interface.
func (s remoteWikiService_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	case "Delete":
		return s.delete
	case "GetVersions":
		return s.getVersions
	case "Load":
		return s.load
	case "Store":
		return s.store
	default:
		return nil
	}
}

func (s remoteWikiService_server_stub) delete(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 uint64
	a0 = dec.Uint64()
	var a1 string
	a1 = dec.String()
	var a2 uint64
	a2 = dec.Uint64()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	appErr := s.impl.Delete(ctx, a0, a1, a2)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s remoteWikiService_server_stub) getVersions(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 uint64
	a0 = dec.Uint64()
	var a1 string
	a1 = dec.String()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.GetVersions(ctx, a0, a1)

	// Encode the results.
	enc := codegen.NewEncoder()
	serviceweaver_enc_slice_RawWikiContent_44c17df6(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s remoteWikiService_server_stub) load(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 uint64
	a0 = dec.Uint64()
	var a1 string
	a1 = dec.String()
	var a2 uint64
	a2 = dec.Uint64()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.Load(ctx, a0, a1, a2)

	// Encode the results.
	enc := codegen.NewEncoder()
	(r0).WeaverMarshal(enc)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s remoteWikiService_server_stub) store(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 uint64
	a0 = dec.Uint64()
	var a1 uint64
	a1 = dec.Uint64()
	var a2 string
	a2 = dec.String()
	var a3 uint64
	a3 = dec.Uint64()
	var a4 string
	a4 = dec.String()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	appErr := s.impl.Store(ctx, a0, a1, a2, a3, a4)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.Error(appErr)
	return enc.Data(), nil
}

// Reflect stub implementations.

type remoteWikiService_reflect_stub struct {
	caller func(string, context.Context, []any, []any) error
}

// Check that remoteWikiService_reflect_stub implements the RemoteWikiService interface.
var _ RemoteWikiService = (*remoteWikiService_reflect_stub)(nil)

func (s remoteWikiService_reflect_stub) Delete(ctx context.Context, a0 uint64, a1 string, a2 uint64) (err error) {
	err = s.caller("Delete", ctx, []any{a0, a1, a2}, []any{})
	return
}

func (s remoteWikiService_reflect_stub) GetVersions(ctx context.Context, a0 uint64, a1 string) (r0 []RawWikiContent, err error) {
	err = s.caller("GetVersions", ctx, []any{a0, a1}, []any{&r0})
	return
}

func (s remoteWikiService_reflect_stub) Load(ctx context.Context, a0 uint64, a1 string, a2 uint64) (r0 RawWikiContent, err error) {
	err = s.caller("Load", ctx, []any{a0, a1, a2}, []any{&r0})
	return
}

func (s remoteWikiService_reflect_stub) Store(ctx context.Context, a0 uint64, a1 uint64, a2 string, a3 uint64, a4 string) (err error) {
	err = s.caller("Store", ctx, []any{a0, a1, a2, a3, a4}, []any{})
	return
}

// AutoMarshal implementations.

var _ codegen.AutoMarshal = (*RawWikiContent)(nil)

type __is_RawWikiContent[T ~struct {
	weaver.AutoMarshal
	Version   uint64
	CreatorId uint64
	CreatedAt int64
	Markdown  string
}] struct{}

var _ __is_RawWikiContent[RawWikiContent]

func (x *RawWikiContent) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("RawWikiContent.WeaverMarshal: nil receiver"))
	}
	enc.Uint64(x.Version)
	enc.Uint64(x.CreatorId)
	enc.Int64(x.CreatedAt)
	enc.String(x.Markdown)
}

func (x *RawWikiContent) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("RawWikiContent.WeaverUnmarshal: nil receiver"))
	}
	x.Version = dec.Uint64()
	x.CreatorId = dec.Uint64()
	x.CreatedAt = dec.Int64()
	x.Markdown = dec.String()
}

// Encoding/decoding implementations.

func serviceweaver_enc_slice_RawWikiContent_44c17df6(enc *codegen.Encoder, arg []RawWikiContent) {
	if arg == nil {
		enc.Len(-1)
		return
	}
	enc.Len(len(arg))
	for i := 0; i < len(arg); i++ {
		(arg[i]).WeaverMarshal(enc)
	}
}

func serviceweaver_dec_slice_RawWikiContent_44c17df6(dec *codegen.Decoder) []RawWikiContent {
	n := dec.Len()
	if n == -1 {
		return nil
	}
	res := make([]RawWikiContent, n)
	for i := 0; i < n; i++ {
		(&res[i]).WeaverUnmarshal(dec)
	}
	return res
}
